greenprep/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('mealbuilder.urls')),
    path('grocerylist/', include('grocerylist.urls')),
    path('profile/', include('userprofile.urls')),
    path('mealcalendar/', include('mealcalendar.urls')),

]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

mealbuilder/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.mealbuilder, name='mealbuilder'),
]

mealcalendar/urls.py
from django.urls import path,include
from . import views

app_name = 'mealcalendar'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='mealcalendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/(<event_id>)/', views.event, name='event_edit'),
    path('meal/new/', views.meal, name='meal_new'),
    path('meal/edit/(<meal_id>)/', views.meal, name='meal_edit'),
]

mealbuilder/models.py
from django.db import models
from django.utils import timezone
from uuid import uuid4
import datetime

# Create your models here.

class Food(models.Model):
    db_num = models.CharField(max_length = 6)
    name = models.CharField(max_length=120)
    category = models.CharField(max_length = 120)
    #serving_sizes(S)  =

    # This amount per 100g?
    #round all macros up to the nearest gram - not doubles when calculating optimal meal?
    calories = models.IntegerField()
    protein = models.FloatField()
    carbs = models.FloatField()
    # fiber = models.DecimalField( decimal_places=2)
    fat = models.FloatField()

    def __str__(self):
        return self.name

    #what other methods should we have?

    #need any "on save" methods?
    #eg convert from "1 spoonful" to value in grams

#---------------------------------------------

class Meal(models.Model):
    creator_id = models.CharField(max_length=120)
    meal_name = models.CharField(max_length=120)
    creation_date = models.DateTimeField(default=timezone.now())

    #list of foods that are in the meal AND the amount of that food that's included

    calories = models.IntegerField(null=True)
    protein = models.FloatField(null=True)
    carbs = models.FloatField(null=True)
    fiber = models.FloatField(null=True)
    fat = models.FloatField(null=True)

    protein_goal = models.IntegerField(null=True)
    carb_goal = models.IntegerField(null=True)
    fat_goal = models.IntegerField(null=True)
    #calculation goal for the meal for fats, protein, and carbs
    #cals, fats, protein, carbs allocated FOR THE MEAL
    #potentially add info for 'bounds' as in 'no more than 20oz chicken please'


    #mini model rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr- holding only many to many relationship to foods, and
    # also the portion of food that will be in it
    #start serving size as null, will change once the food has been added in?
    #or does the class just hold on to these values and work only with the food objects, then
    #come back and populate the meal object
    #because like, the algorithm needs to know the foods to be able to calculate the serving sizes
    def get_html_url(self):
        url = reverse('mealcalendar:meal_edit', args=(self.id,))
        return '<a href="{url}"> {name} </a>'.format(url=url,name=self.meal_name)

    def __str__(self):
        return self.meal_name

    def updateNutrients(self):
        self.protein = 0
        self.carbs = 0
        self.fat = 0
        self.calories = 0

        for item in self.mealitem_set.all():
            self.protein = self.protein + item.protein
            self.carbs = self.carbs + item.carbs
            self.fat = self.fat + item.fat
            self.calories = self.calories + item.calories
            self.save()

    class Meta:
        ordering = ['creation_date']


#---------------------------------------------

# MealItem objects are unique to their meals - even if several meals all contain
# 1 serving of chicken, new identical objects will be created for all of them
class MealItem(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.PROTECT)
    food = models.ForeignKey(Food, on_delete=models.PROTECT)
    #per 100g portion - this is what the USDA database provides for all entries
    quantity = models.FloatField(null=True)
    limit = models.IntegerField(null=True)
    protein = models.FloatField(null=True)
    carbs = models.FloatField(null=True)
    fat = models.FloatField(null=True)
    calories = models.IntegerField(null=True)

    def __str__(self):
        return str(self.id)

    def updateNutrients(self):
        self.protein = self.food.protein * self.quantity
        self.carbs = self.food.carbs * self.quantity
        self.fat = self.food.fat * self.quantity
        self.calories = self.food.calories * self.quantity
        self.save()

#---------------------------------------------


class Day(models.Model):
    date = models.DateTimeField()
    #user id of user whose day this is
    num_of_meals = models.IntegerField()
    #array of meal objects

    def __str__(self):
        return self.id

mealbuilder/forms.py
from django import forms
from .models import Food, Meal

from django.forms import ModelForm, DateInput


class MealBuilderForm(ModelForm):

    food_1 = forms.ModelChoiceField(initial=Food.objects.get(pk=535),queryset=Food.objects.all().order_by('name'))
    food_1_limit = forms.IntegerField(required=False)
    food_2 = forms.ModelChoiceField(initial=Food.objects.get(pk=1860),queryset=Food.objects.all().order_by('name'))
    food_2_limit = forms.IntegerField(required=False)

    class Meta:
        model = Meal
        fields = ('meal_name','creation_date','protein_goal','carb_goal','fat_goal',)


    def __init__(self, *args, **kwargs):
        super(MealBuilderForm, self).__init__(*args, **kwargs)

mealbuilder/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .forms import MealBuilderForm
from .models import Food, Meal, MealItem
from .simplex import OptimizeMeal

def mealbuilder(request):

    context = {
        'message': 'Hello, world. You\'re at the mealbuilder index.',
    }

    if request.method == 'POST':
        form = MealBuilderForm(request.POST)
        if form.is_valid():
            meal = CreateMealFromFormData(form)
            optimized_meal = OptimizeMeal(meal)
            context.update({
                'optimized_meal': meal,
                'message': meal.meal_name + " successfully created",
            })

    else:
        form = MealBuilderForm()

    context.update({
        'form': form,
    })
    return render(request, 'mealbuilder.html', context=context)


def CreateMealFromFormData(form):
    meal = Meal(
        meal_name = form.cleaned_data.get('meal_name'),
        protein_goal = form.cleaned_data.get('protein_goal'),
        carb_goal = form.cleaned_data.get('carb_goal'),
        fat_goal = form.cleaned_data.get('fat_goal')
    )
    meal.save()

    meal_item_1 = meal.mealitem_set.create(
        food = form.cleaned_data.get('food_1'),
        limit = form.cleaned_data.get('food_1_limit')
    )
    meal_item_1.save()


    meal_item_2 = meal.mealitem_set.create(
        food = form.cleaned_data.get('food_2'),
        limit = form.cleaned_data.get('food_2_limit')
    )
    meal_item_2.save()

    return meal

mealbuilder/templates/base_generic.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  {% block title %}<title>Green Prep</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'mealcalendar/css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          Hello, <a href="{% url 'profile' %}"> {{user.get_username}}</a><br/>
          <a href="{% url 'mealbuilder' %}">Meal Builder</a><br/>
          <a href="{% url 'grocerylist' %}">Grocery List</a><br/>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

mealbuilder/templates/mealbuilder.html
{% extends "base_generic.html" %}

{% block title %}
Meal
{% endblock %}
{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'mealcalendar:mealcalendar' %}"> Calendar </a>
</div>
<p> {{message}} </p>

<h2>Create Meal</h2>
  <form method="post">
    {% csrf_token %}
    <table class="form form-table">
      {{ form }}
      <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Optimize Meal </button></td></tr>
    </table>
  </form>

{% endblock %}